### ISSUE TITLE
Speed up database initialization on fresh installs

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/rogerthat-ios-client#65] opened 2017-01-24 11:16 UTC
The initial database setup takes a lot of time on older phones. iOS kills the app if it takes more than 10 seconds, possibly breaking the database.

We need a setup script from version 0 to version 73 + support for upgrading from 73 to 74, if 74 would exists at that time.

**Comment by RubenMattan** [comment] 2017-07-13 12:05
duplicate of https://github.com/rogerthat-platform/rogerthat-ios-client/issues/106

**Closed** 2017-07-13 12:25 UTC
Labels: process_duplicate, type_feature
